accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings

from .views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
    SkillListView,
    )

urlpatterns = [
    path('post/<int:pk>/delete/', BlogDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('', BlogListView.as_view(), name ='home'),
    path('skill/', SkillListView.as_view(), name ='skill'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings
from blog.views import AboutPageView

urlpatterns = [
    path('about/', AboutPageView.as_view(), name='about'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls')),
    path('', include('sendemail.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sendemail/urls.py
from django.contrib import admin
from django.urls import path

from .views import emailView, successView

urlpatterns = [
    path('email/', emailView, name='email'),
    path('success/', successView, name='success'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext
from ckeditor.fields import RichTextField


class Post(models.Model):
    title = models.CharField(max_length=200)
    # author = models.ForeignKey(
    #     'auth.User',
    #     on_delete=models.CASCADE,
    # )
    created_at = models.DateTimeField(auto_now_add=True)
    body = RichTextField()
    cover = models.ImageField(upload_to='images/', blank=True, null=True)

    # translations = TranslatedFields(
    # title = models.CharField(max_length=250)
    # )
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    class Meta:
        ordering = ['-created_at', ]


class Skill(models.Model):
    title = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True)
    body = RichTextField(config_name='default')

    def __str__(self):
        return self.title

sendemail/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from .models import Post
from hvad.forms import TranslatableModelForm


class PostForm(TranslatableModelForm):

    class Meta:
        model = Post
        fields = ('title', 'body',)

sendemail/forms.py
from django import forms

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

blog/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView
from .models import Post, Skill
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils import translation
from django.shortcuts import render_to_response
from django.views.generic import TemplateView


class BlogListView(ListView):
    # user_languange = 'pl'
    # translation.activate(user_languange)
    # .sessiIon[translation.LANGUAGE_SESSION_KEY] = user_languange
    model = Post
    fields = '__all__'
    template_name = 'home.html'

class BlogDetailView(DetailView):
    model = Post
    fields = '__all__'
    template_name = 'post_detail.html'

class BlogCreateView(CreateView):
    model = Post
    template_name = 'post_new.html'
    fields = '__all__'

class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'post_edit.html'
    fields = ['title', 'body']

class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('home')

class SkillListView(ListView):
    model = Skill
    template_name = 'skill.html'
    fields = '__all__'

class AboutPageView(TemplateView):
    template_name = "about.html"

sendemail/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm

def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['admin@mismail.xyz'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('success')
    return render(request, "email.html", {'form': form})

def successView(request):
    return HttpResponse('Success! Thank you for your message.')

templates/about.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}


    <h1>Michalina Andrzejewska</h1>
    <p>{% trans "Aspiring programmer" %}</p>



    <!-- Introduction-->

    <p>
        {% trans "I thought I could be a great medical doctor. I still think, I could. I believe though I could be an even better programmer." %}
    </p>


    <hr>

    <h2><a style="color:#243d0e" href="https://github.com/andrmich">
        <img src ="/static/img/GitHub-Mark-32px.png">GitHub</a></h2>
    {#				<a href="#"><img src="img/re.png" class="grid-2"></a>#}
    {#				<a href="#"><img src="img/re.png" class="grid-2"></a>#}
    {#				<a href="#"><img src="img/re.png" class="grid-2"></a>#}
    {#				<a href="#"><img src="img/re.png" class="grid-2"></a>#}
    {#				<a href="#"><img src="img/re.png" class="grid-2"></a>#}
    </div>
    </section>
{% endblock content %}

templates/base.html
{% load static i18n %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href='{% static 'css/base.css' %}' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Coiny|Roboto+Slab" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


    <link rel="icon" href='{% static 'img/favicon.ico' %}'/>
    <title>{% trans "Code all day long!" %}</title>
</head>
<body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

<div>

<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white"<a href="{% url 'home' %}">{% trans "Code all day long!" %}</a></h4>
        <h1 class="text-white">Michalina Andrzejewska</h1>
    <p class="text-white">{% trans "Aspiring programmer" %}</p>
          <p class="text-muted">{% trans "I thought I could be a great medical doctor. I still think, I could. I believe though I could be an even better programmer." %} </p>
        <form class="language" action="{% url 'set_language' %}" method="post">{% csrf_token %}
                <input type="hidden" name="next" value="{{ redirect_to }}">
                <select name="language">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}
                                selected {% endif %}>
                            {{ language.name }}
                        </option>
                    {% endfor %}
                <input type="submit" class="hamburger" value="Go"/>
                </select>
             </form>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
{#          <h4 class="text-white">{% trans 'Contact' %}</h4>#}
          <ul class="list-unstyled">
            <li><a href="{% url 'home' %}" class="text-white">{% trans "Home" %}</a></li>
            <li><a  href="{% url 'skill' %}" class="text-white">{% trans "Skills" %}</a></li>
            <li><a href="https://github.com/andrmich" class="text-white">GitHub</a></li>
              <li><a  href="{% url 'email' %}" class="text-white">{% trans "Contact me" %}</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="{% url 'home' %}" class="navbar-brand d-flex align-items-center">
{#        <img src="static/img/favicon.ico" height="20" width="20"/>#}
        <strong>Greengrapes</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>
<div class="container-fluid">
    <!--{% if user.is_authenticated %}
      <p>Hi {{user.username}}!</p>
      <p><a href="{% url 'logout' %}">Log out</a> </p>
      <div class="nav-right">
        <a href="{% url 'post_new' %}">+ New Blog Post</a>
      {% else %}
        <h2>{% trans "Hi! Welcome to my blog! " %}</h2> -->
        <!-- <p>You are not logged in.</p>
      <a href="{% url 'login' %}">Log In</a> -->
        <!-- {% endif %} -->
    {% block content %}
    {% endblock content %}

</div>
</body>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="{{ site.url }}/">Visit the homepage</a> or read our <a href="{{ site.baseurl }}/docs/{{ site.docs_version }}/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>



{##}
{#    <header>#}
{#        <div class="page-header">#}
{#            <h1>/h1>#}
{#        </div>#}
{#    </header>#}
{##}
{##}
{#    <ul class="nav nav-pills">#}
{#        <li class="nav-item">#}
{#            <a class="nav-link" href="{% url 'home' %}">Home</a>#}
{#        </li>#}
{#        <li class="nav-item">#}
{#            <a class="nav-link" href="{% url 'skill' %}">Skills</a>#}
{#        </li>#}
{##}
{#        <li class="nav-item">#}
{#            <a class="nav-link" href="{% url 'about' %}">About me</a>#}
{#        </li>#}
{#        <li  class="language">#}
{#             <form class="language" action="{% url 'set_language' %}" method="post">{% csrf_token %}#}
{#                <input type="hidden" name="next" value="{{ redirect_to }}">#}
{#                <select name="language">#}
{#                    {% get_current_language as LANGUAGE_CODE %}#}
{#                    {% get_available_languages as LANGUAGES %}#}
{#                    {% get_language_info_list for LANGUAGES as languages %}#}
{#                    {% for language in languages %}#}
{#                        <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}#}
{#                                selected {% endif %}>#}
{#                            {{ language.name }}#}
{#                        </option>#}
{#                    {% endfor %}#}
{#                <input type="submit" class="hamburger" value="Go"/>#}
{#                </select>#}
{#             </form>#}
{#        </li>#}
{#    </ul>#}

{#<footer>#}
{#     Design Credits: <a target="_blank" href="https://www.vecteezy.com">www.Vecteezy.com</a>#}
{#</footer>#}
{#</html>#}

templates/email.html
{% extends 'base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}

<h1>{% trans "Contact me"%}</h1>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-actions">
      <button type="submit">Send</button>
    </div>
</form>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}


<!-- #  {% get_current_language as LANGUAGE_CODE %}

#  <h1>{{ LANGUAGE_CODE }}</h1> -->

  <!-- <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input type="hidden" name="next" value="{{ redirect_to }}">
    <select name="language">
      {% get_current_language as LANGUAGE_CODE %}
      {% get_available_languages as LANGUAGES %}
      {% get_language_info_list for LANGUAGES as languages %}
      {% for language in languages %}
      <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
        {{ language.name_local }} ({{ language.code }})
        </option>
        {% endfor %}
    </select>
    <input type="submit" class="btn btn-secondary" value="Go"/> -->

    </form>
  {% for post in object_list %}
    <div class="post-entry">

      <h2><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2>
      {{ post.body | safe}}
{#       <img src="{{ post.cover.url }}" alt="{{ post.title }}">#}
        <hr>
        <p>published: {{ post.created_at }}</p>

<br>
      </div>
      {% endfor %}
{% endblock content %}

templates/post_delete.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<h1>Delete post</h1>
<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{post.title}}"?</p>
  <input type="submit" value="Confirm"/>
</form>

{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
  <div class="post-entry">
  <h2>  {{post.title}} </h2>
    {{post.body | safe}}
{#     <img src="{{ post.cover.url }}" alt = "{{ post.title }}">#}
    <footer>{{post.created_at}}</footer>
  </div>

  <a href="{% url 'post_edit' post.pk %}">Edit Blog Post</a>
    <a href="{% url 'post_delete' post.pk %}">Delete Blog Post</a>

{% endblock content %}

templates/post_edit.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
  <h1>Edit post</h1>
  <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
  </form>
{% endblock content %}

templates/post_new.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
  <h1>New post</h1>
  <form action="" method="post">{% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save"/>
  </form>

{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock content %}

templates/skill.html
{% extends 'base.html' %}
{% load static %}

{% load static i18n %}

{% block content %}

    <main role="main">

        <section class="jumbotron text-center">
            <div class="container">
                <h1 class="jumbotron-heading">{% trans "Skills" %}</h1>
                <p class="lead text-muted">{% trans "All tutorials, books, workshops..." %}</p>
                {#      <p>#}
                {#        <a href="#" class="btn btn-primary my-2">Main call to action</a>#}
                {#        <a href="#" class="btn btn-secondary my-2">Secondary action</a>#}
                {#      </p>#}
            </div>
        </section>

        {% for skill in skill_list %}
<div class="skill">


                <h3 class="card-text">{{ skill.title}}</h3>
                <p class="card-text">{{ skill.body | safe }}</p>
                <p class="card-text-date">{{ skill.date }}</p>


                </div>

{% endfor %}

    </main>



{% endblock content %}

templates/test_base.html
{% load static i18n %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href='{% static 'css/base.css' %}' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Coiny|Roboto+Slab" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


    <link rel="icon" href='{% static 'img/favicon.ico' %}'/>
    <title>{% trans "Code all day long!" %}</title>
</head>
<body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

<div>
    <header>
        <div class="page-header">
            <h1><a href="{% url 'home' %}">{% trans "Code all day long!" %}</a></h1>
        </div>
    </header>


    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'skill' %}">Skills</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About me</a>
        </li>
        <li>
            <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                <input type="hidden" name="next" value="{{ redirect_to }}">
                <select name="language">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}
                                selected {% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                    {% endfor %}
                </select>
                <input type="submit" class="btn btn-link" value="Go"/>
        </li>
</div>
<!-- <li class="nav-item">
  <a class="nav-link" href="#">Link</a>
</li>
<li class="nav-item">
  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
</li> -->
</ul>
<div class="container-fluid">
    <!-- {% if user.is_authenticated %}
      <p>Hi {{user.username}}!</p>
      <p><a href="{% url 'logout' %}">Log out</a> </p>
      <div class="nav-right">
        <a href="{% url 'post_new' %}">+ New Blog Post</a>
      {% else %}
        <h2>{% trans "Hi! Welcome to my blog! " %}</h2> -->
        <!-- <p>You are not logged in.</p>
      <a href="{% url 'login' %}">Log In</a> -->
        <!-- {% endif %} -->
    {% block content %}
    {% endblock content %}

</div>
</body>
</html>